### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by ojwb** [FabriceColin/pinot#7]
The last release was more than 4.5 years ago (2015/06/11) and there have been various useful improvements since.

**Comment by FabriceColin** [comment]
Thanks for filing this. I had started on that in December and needed some encouragement to finish.
See https://github.com/FabriceColin/pinot/releases/tag/1.10
Let me know if you see any issue...

**Comment by ojwb** [comment]
Great - this looks good, and completely clears the pile of patches we've accumulated in the Debian packaging.

I've prepared a new Debian package of this, but will wait to upload for a few days so the previous upload can migrate to testing.
