### ISSUE TITLE
Cannot index and There are no clear indicator if it works.

### ISSUE THREAD

**Issue by shenlebantongying** [FabriceColin/pinot#9]
I compiled the software and added my path with a lot of PDF files, but it doesn't seem to work.

I have Poppler install and `pdftotext` is in the PATH

The `status` always say that no file is indexed, and there are no clear indicator how to trigger the index.

How can trigger the index?
<img src="https://user-images.githubusercontent.com/20123683/134860232-5750c29f-bcea-4713-a649-38a0c2855f61.png" width="600"/>
<img src="https://user-images.githubusercontent.com/20123683/134860362-4f31481e-7e9b-490a-9b17-85a7481851db.png" width="600"/>

**Comment by FabriceColin** [comment]
The "Xapian Omega" plugin is to query a locally installed instance of Omega (http://localhost/).

The contents of the ~/Zotero directory will be indexed in "My Documents". Try searching that instead, or better list this index with the "Options > List Contents Of" menu.

If in doubt, try resetting the index with the instructions in the README's "How to reset indexes" section.

If this doesn't help, let me know what OS/distribution/package this is with and confirm whether this is 1.10.
